export const ROUTE = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  ADMIN_DASHBOARD: '/admin/dashboard/',
  ADMIN_BLOG_ARCHIVE: '/admin/blog/archive/',
  ADMIN_BLOG_CREATE: '/admin/blog/create/',
  ADMIN_BLOG_EDIT: '/admin/blog/edit/',
  ADMIN_BLOG_TAG_ARCHIVE: '/admin/blog/tag/',
  ADMIN_BLOG_TAG_EDIT: '/admin/blog/tag/edit/',
  ADMIN_RECIPE_ARCHIVE: '/admin/recipe/archive/',
  ADMIN_RECIPE_CREATE: '/admin/recipe/create/',
  ADMIN_RECIPE_EDIT: '/admin/recipe/edit/',
  ADMIN_RECIPE_TAG_ARCHIVE: '/admin/recipe/tag/archive/',
  ADMIN_RECIPE_TAG_CREATE: '/admin/recipe/tag/create/',
  ADMIN_RECIPE_TAG_EDIT: '/admin/recipe/tag/edit/',
  ADMIN_FLAVOR_ARCHIVE: '/admin/flavor/archive/',
  ADMIN_FLAVOR_CREATE: '/admin/flavor/create/',
  ADMIN_FLAVOR_EDIT: '/admin/flavor/edit/',
  ADMIN_FLAVOR_BRAND_ARCHIVE: '/admin/flavor/brand/archive/',
  ADMIN_FLAVOR_BRAND_CREATE: '/admin/flavor/brand/create/',
  ADMIN_FLAVOR_BRAND_EDIT: '/admin/flavor/brand/edit/',
}
