import Head from 'next/head'
import { ArticleItem } from 'pages/components/ArticleItem'
import { UserLayout } from 'pages/layout/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <UserLayout>
        <ul className='flex flex-wrap gap-12'>
          <ArticleItem />
          <ArticleItem />
          <ArticleItem />
          <ArticleItem />
          <ArticleItem />
          <ArticleItem />
          <ArticleItem />
          <ArticleItem />
        </ul>
      </UserLayout>
    </div>
  )
}
