import Head from 'next/head'

import { BlogArticleForUser } from 'pages/components/Article'
import { UserLayout } from 'pages/layout/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <UserLayout>
        <BlogArticleForUser />
      </UserLayout>
    </div>
  )
}
